version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/test/crs"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/test/e2e"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/tools/cachectl"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/tools/crs-converter"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/test/playwright"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/waf-dashboard"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "wafctl"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      all:
        patterns:
          - "*"