package main

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"
)

// deployMu serializes all deploy operations (WAF, RL, CSP) to prevent
// interleaved file writes and Caddy reloads from concurrent requests.
var deployMu sync.Mutex

// DeployConfig holds paths and settings for the deploy pipeline.
type DeployConfig struct {
	// CorazaDir is the directory for custom Coraza config files.
	// These files are volume-mounted into the Caddy container.
	CorazaDir string

	// RateLimitDir is the directory for per-zone rate limit .caddy files.
	// These files are volume-mounted into the Caddy container and imported
	// by each site block via glob patterns.
	RateLimitDir string

	// CSPDir is the directory for per-service CSP header .caddy files.
	// These files are volume-mounted into the Caddy container and imported
	// by each site block via glob patterns.
	CSPDir string

	// CaddyfilePath is the path to the Caddyfile (read-only mount from Caddy).
	// Used to POST to Caddy's admin API for reload.
	CaddyfilePath string

	// CaddyAdminURL is the base URL for Caddy's admin API.
	CaddyAdminURL string

	// PolicyRulesFile is the path to the policy-rules.json file consumed by
	// the caddy-policy-engine plugin. Generated by wafctl when the policy
	// engine is enabled. The plugin hot-reloads this file via mtime polling.
	PolicyRulesFile string

	// PolicyEngineEnabled controls whether allow/block/honeypot exclusions
	// are routed to the Caddy policy engine plugin (true) or remain as
	// Coraza SecRules (false). Default false for safe rollback.
	PolicyEngineEnabled bool
}

// DeployResponse is returned by the deploy endpoint.
type DeployResponse struct {
	Status      string `json:"status"`
	Message     string `json:"message"`
	PreCRS      string `json:"pre_crs_file"`
	PostCRS     string `json:"post_crs_file"`
	WAFSettings string `json:"waf_settings_file"`
	Reloaded    bool   `json:"reloaded"`
	Timestamp   string `json:"timestamp"`
}

// ensureCorazaDir creates the coraza config directory and empty placeholder
// files if they don't exist. Called at startup.
func ensureCorazaDir(dir string) error {
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("creating coraza dir %s: %w", dir, err)
	}

	placeholders := map[string]string{
		"custom-pre-crs.conf":  "",
		"custom-post-crs.conf": "",
		// The WAF settings placeholder includes SecRuleEngine On as the safe
		// default. The Caddyfile intentionally does NOT set SecRuleEngine —
		// this file is the single source of truth, managed by the generator.
		"custom-waf-settings.conf": "SecRuleEngine On\n",
	}
	for name, extra := range placeholders {
		path := filepath.Join(dir, name)
		if _, err := os.Stat(path); os.IsNotExist(err) {
			header := fmt.Sprintf("# Managed by wafctl\n# Created: %s\n# This file is empty until settings are deployed.\n%s",
				time.Now().UTC().Format(time.RFC3339), extra)
			if err := atomicWriteFile(path, []byte(header), 0644); err != nil {
				return fmt.Errorf("creating placeholder %s: %w", path, err)
			}
			log.Printf("created placeholder: %s", path)
		}
	}
	return nil
}

// generateOnBoot regenerates all config files from stored state at startup.
// This ensures a stack restart always picks up the latest generator output
// without requiring a manual POST /api/config/deploy.
// No Caddy reload is performed — Caddy reads the files fresh on its own start.
func generateOnBoot(cs *ConfigStore, es *ExclusionStore, rs *RateLimitRuleStore, cspStore *CSPStore, secStore *SecurityHeaderStore, ls *ManagedListStore, ds *DefaultRuleStore, deployCfg DeployConfig) {
	// WAF config: generate exclusion rules + WAF settings.
	cfg := cs.Get()
	allExclusions := es.EnabledExclusions()

	// When policy engine is enabled, allow/block/honeypot go to the plugin's
	// JSON file instead of Coraza SecRules. Filter them out before generation.
	exclusions := FilterSecRuleExclusions(allExclusions, deployCfg.PolicyEngineEnabled)
	result := GenerateConfigs(cfg, exclusions, ls)
	wafSettings := GenerateWAFSettings(cfg)

	// Validate generated config at boot to catch issues early.
	vr := ValidateGeneratedConfig(result.PreCRS, result.PostCRS, wafSettings)
	selfRefWarnings := validateGeneratedRuleIDs(exclusions)
	vr.Warnings = append(vr.Warnings, selfRefWarnings...)
	logValidationResult(vr)

	if err := writeConfFiles(deployCfg.CorazaDir, result.PreCRS, result.PostCRS, wafSettings); err != nil {
		log.Printf("[boot] warning: failed to generate WAF configs: %v", err)
	} else {
		log.Printf("[boot] regenerated WAF configs (%d exclusions, mode=%s, paranoia=%d)",
			len(exclusions), cfg.Defaults.Mode, cfg.Defaults.ParanoiaLevel)
	}

	// Rate limit rules: discover new services from the Caddyfile.
	rs.MergeCaddyfileServices(deployCfg.CaddyfilePath)

	// Policy engine: generate JSON rules file for the Caddy plugin.
	// Includes both WAF exclusions (allow/block) and rate limit rules.
	if deployCfg.PolicyEngineEnabled && deployCfg.PolicyRulesFile != "" {
		rlRules := rs.EnabledRules()
		rlGlobal := rs.GetGlobal()
		svcMap := BuildServiceFQDNMap(deployCfg.CaddyfilePath)
		respHeaders := BuildPolicyResponseHeaders(cspStore, secStore, svcMap)
		wafCfg := BuildPolicyWafConfig(cs, svcMap)
		policyData, err := GeneratePolicyRulesWithRL(allExclusions, rlRules, rlGlobal, ls, svcMap, respHeaders, wafCfg)
		if err != nil {
			log.Printf("[boot] warning: failed to generate policy rules: %v", err)
		} else {
			// Apply default rule overrides (disabled IDs + field overrides).
			policyData, err = ApplyDefaultRuleOverrides(policyData, ds)
			if err != nil {
				log.Printf("[boot] warning: failed to apply default rule overrides: %v", err)
			} else if err := atomicWriteFile(deployCfg.PolicyRulesFile, policyData, 0644); err != nil {
				log.Printf("[boot] warning: failed to write policy rules file: %v", err)
			} else {
				policyCount := 0
				for _, e := range allExclusions {
					if IsPolicyEngineType(e.Type) {
						policyCount++
					}
				}
				log.Printf("[boot] regenerated policy rules (%d WAF + %d RL rules) → %s",
					policyCount, len(rlRules), deployCfg.PolicyRulesFile)
			}
		}
	}

	// Rate limit Caddyfile generation: only needed when policy engine is
	// disabled (legacy mode). When enabled, RL rules are in policy-rules.json
	// and stale .caddy files are cleared to prevent double rate limiting.
	if !deployCfg.PolicyEngineEnabled {
		rules := rs.EnabledRules()
		global := rs.GetGlobal()
		rlFiles := GenerateRateLimitConfigs(rules, global, deployCfg.CaddyfilePath, ls)
		if len(rlFiles) > 0 {
			written, err := writeRLFiles(deployCfg.RateLimitDir, rlFiles)
			if err != nil {
				log.Printf("[boot] warning: failed to generate rate limit configs: %v", err)
			} else {
				log.Printf("[boot] regenerated %d rate limit files", len(written))
			}
		}
	} else {
		// Clear stale RL .caddy files to prevent double rate limiting
		// (policy engine + caddy-ratelimit plugin both enforcing the same rules).
		clearRLFiles(deployCfg.RateLimitDir)
	}

	// CSP headers are now handled by the policy engine plugin via
	// response_headers in policy-rules.json (no .caddy file generation needed).
}

// deployAll regenerates all WAF and policy engine config files and reloads Caddy.
// This is the programmatic equivalent of POST /api/config/deploy, used by
// background processes (e.g. blocklist refresh) that need to trigger a full
// regeneration + reload cycle after updating managed lists.
func deployAll(cs *ConfigStore, es *ExclusionStore, rs *RateLimitRuleStore, ls *ManagedListStore, cspStore *CSPStore, secStore *SecurityHeaderStore, ds *DefaultRuleStore, deployCfg DeployConfig) error {
	deployMu.Lock()
	defer deployMu.Unlock()

	cfg := cs.Get()
	allExclusions := es.EnabledExclusions()

	// SecRule generation (excluding policy engine types).
	exclusions := FilterSecRuleExclusions(allExclusions, deployCfg.PolicyEngineEnabled)
	result := GenerateConfigs(cfg, exclusions, ls)
	wafSettings := GenerateWAFSettings(cfg)

	if err := writeConfFiles(deployCfg.CorazaDir, result.PreCRS, result.PostCRS, wafSettings); err != nil {
		return fmt.Errorf("writing WAF config files: %w", err)
	}

	// Policy engine: generate JSON rules file (includes RL rules when enabled).
	if deployCfg.PolicyEngineEnabled && deployCfg.PolicyRulesFile != "" {
		rlRules := rs.EnabledRules()
		rlGlobal := rs.GetGlobal()
		svcMap := BuildServiceFQDNMap(deployCfg.CaddyfilePath)
		respHeaders := BuildPolicyResponseHeaders(cspStore, secStore, svcMap)
		wafCfg := BuildPolicyWafConfig(cs, svcMap)
		policyData, err := GeneratePolicyRulesWithRL(allExclusions, rlRules, rlGlobal, ls, svcMap, respHeaders, wafCfg)
		if err != nil {
			return fmt.Errorf("generating policy rules: %w", err)
		}
		policyData, err = ApplyDefaultRuleOverrides(policyData, ds)
		if err != nil {
			return fmt.Errorf("applying default rule overrides: %w", err)
		}
		if err := atomicWriteFile(deployCfg.PolicyRulesFile, policyData, 0644); err != nil {
			return fmt.Errorf("writing policy rules file: %w", err)
		}
		policyCount := 0
		for _, e := range allExclusions {
			if IsPolicyEngineType(e.Type) {
				policyCount++
			}
		}
		log.Printf("[deploy] wrote policy rules (%d WAF + %d RL rules) → %s",
			policyCount, len(rlRules), deployCfg.PolicyRulesFile)
	}

	// Sync rate limit Caddyfile snippets (legacy mode only).
	if !deployCfg.PolicyEngineEnabled {
		syncCaddyfileServices(rs, ls, deployCfg)
	}

	// Reload Caddy.
	confFiles := []string{
		filepath.Join(deployCfg.CorazaDir, "custom-pre-crs.conf"),
		filepath.Join(deployCfg.CorazaDir, "custom-post-crs.conf"),
		filepath.Join(deployCfg.CorazaDir, "custom-waf-settings.conf"),
	}
	if err := reloadCaddy(deployCfg.CaddyfilePath, deployCfg.CaddyAdminURL, confFiles...); err != nil {
		return fmt.Errorf("Caddy reload: %w", err)
	}

	return nil
}

// writeConfFiles writes the generated pre-CRS, post-CRS, and WAF settings configs to disk atomically.
func writeConfFiles(dir, preCRS, postCRS, wafSettings string) error {
	files := map[string]string{
		"custom-pre-crs.conf":      preCRS,
		"custom-post-crs.conf":     postCRS,
		"custom-waf-settings.conf": wafSettings,
	}
	for name, content := range files {
		path := filepath.Join(dir, name)
		if err := atomicWriteFile(path, []byte(content), 0644); err != nil {
			return fmt.Errorf("writing %s: %w", path, err)
		}
		log.Printf("wrote %s (%d bytes)", path, len(content))
	}
	return nil
}

// reloadCaddy sends the Caddyfile to Caddy's admin API to trigger a reload.
// This reads the Caddyfile from disk and POSTs it to /load with the caddyfile adapter.
//
// The Caddyfile adapter strips comments during conversion to JSON, so even when
// included files (e.g. custom-waf-settings.conf, custom-pre-crs.conf) change on
// disk, the adapted JSON is byte-identical to the running config. Caddy's
// changeConfig() compares via bytes.Equal() and silently skips reload on match.
//
// We solve this with Cache-Control: must-revalidate, which sets forceReload=true
// in Caddy's admin handler, bypassing the bytes.Equal() gate entirely. This
// forces a full re-provision of all modules — including Coraza, which re-reads
// its Include files at provision time.
//
// The fingerprint comment is still prepended for logging/diagnostics but is NOT
// relied upon for forcing the reload.
func reloadCaddy(caddyfilePath, adminURL string, configFiles ...string) error {
	content, err := os.ReadFile(caddyfilePath)
	if err != nil {
		return fmt.Errorf("reading Caddyfile at %s: %w", caddyfilePath, err)
	}

	// Build a fingerprint from all config file contents for logging/diagnostics.
	// This does NOT force the reload (Cache-Control header does that) but lets
	// us track what changed across deploys in the log output.
	fingerprint := deployFingerprint(configFiles)
	header := fmt.Sprintf("# wafctl deploy %s fingerprint:%s\n",
		time.Now().UTC().Format(time.RFC3339), fingerprint)
	payload := append([]byte(header), content...)

	url := adminURL + "/load"
	req, err := http.NewRequest("POST", url, bytes.NewReader(payload))
	if err != nil {
		return fmt.Errorf("creating reload request: %w", err)
	}
	req.Header.Set("Content-Type", "text/caddyfile")
	// Force Caddy to reload even when the adapted JSON is byte-identical to
	// the running config. Without this, Caddy's changeConfig() compares the
	// adapted JSON via bytes.Equal() and silently skips the reload when it
	// matches — which it always does because our fingerprint comment is
	// stripped during Caddyfile-to-JSON adaptation. The "must-revalidate"
	// value sets forceReload=true in Caddy's admin handler, bypassing the
	// bytes.Equal() gate entirely and forcing a full re-provision of all
	// modules (including Coraza, which re-reads its Include files).
	// See: caddy.go changeConfig() and admin.go handleLoadConfig().
	req.Header.Set("Cache-Control", "must-revalidate")

	client := &http.Client{Timeout: 120 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("Caddy admin API request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("Caddy reload failed (status %d): %s", resp.StatusCode, string(body))
	}

	log.Printf("Caddy reload successful via %s (fingerprint: %s)", url, fingerprint)
	return nil
}

// deployFingerprint computes a short SHA-256 hash of the concatenated contents
// of the given file paths. If a file can't be read, its path is hashed instead
// (so the fingerprint still changes when files are added/removed).
func deployFingerprint(paths []string) string {
	h := sha256.New()
	for _, p := range paths {
		data, err := os.ReadFile(p)
		if err != nil {
			// File missing or unreadable — hash the path itself as a marker.
			h.Write([]byte(p))
		} else {
			h.Write(data)
		}
	}
	return fmt.Sprintf("%x", h.Sum(nil))[:16]
}

// clearRLFiles replaces all *_rl.caddy files in the RL directory with
// comment-only placeholders. This prevents the caddy-ratelimit plugin from
// enforcing stale rules when rate limiting has moved to the policy engine.
func clearRLFiles(rlDir string) {
	if rlDir == "" {
		return
	}
	entries, err := os.ReadDir(rlDir)
	if err != nil {
		return // directory doesn't exist yet — nothing to clear
	}
	cleared := 0
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), "_rl.caddy") {
			continue
		}
		path := filepath.Join(rlDir, e.Name())
		placeholder := fmt.Sprintf("# Rate limiting managed by policy engine plugin\n# File cleared at %s\n",
			time.Now().UTC().Format(time.RFC3339))
		if err := atomicWriteFile(path, []byte(placeholder), 0644); err != nil {
			log.Printf("[boot] warning: failed to clear stale RL file %s: %v", path, err)
			continue
		}
		cleared++
	}
	if cleared > 0 {
		log.Printf("[boot] cleared %d stale RL .caddy files (policy engine handles rate limiting)", cleared)
	}
}
