package main

import (
	"strconv"
	"strings"
	"time"
)

// headerValue extracts the first value for a header key from a map[string][]string.
// Tries the exact key first, then a case-insensitive match.
func headerValue(headers map[string][]string, key string) string {
	if vals, ok := headers[key]; ok && len(vals) > 0 {
		return vals[0]
	}
	// Case-insensitive fallback.
	lowerKey := strings.ToLower(key)
	for k, vals := range headers {
		if strings.ToLower(k) == lowerKey && len(vals) > 0 {
			return vals[0]
		}
	}
	return ""
}

// parseEvent normalizes a raw audit log entry into an Event.
func parseEvent(entry AuditLogEntry) Event {
	tx := entry.Transaction

	ts := parseTimestamp(tx.Timestamp)

	ua := headerValue(tx.Request.Headers, "User-Agent")

	eventType := "logged"
	if tx.IsInterrupted {
		eventType = "blocked"
	}

	// Classify events by checking rule IDs from custom rule ranges.
	// Scan all messages to find the highest-priority classification.
	// Priority: policy engine > default (blocked/logged).
	var candidateType string
	for _, m := range entry.Messages {
		rid := m.Data.ID

		// Policy Engine rules — generated by the UI.
		// Highest priority — immediately finalize.
		if rid >= policyRuleIDMin && rid <= policyRuleIDMax {
			msg := m.Data.Msg
			if strings.HasPrefix(msg, "Policy Allow:") {
				candidateType = "policy_allow"
			} else if strings.HasPrefix(msg, "Policy Skip:") {
				// A skip_rule exclusion fired, but the request may still be
				// blocked by other CRS rules the skip didn't cover. Only
				// classify as "policy_skip" if the request was NOT interrupted.
				if !tx.IsInterrupted {
					candidateType = "policy_skip"
				}
				// If still interrupted, leave candidateType empty so the
				// default "blocked" classification is preserved.
			} else if strings.HasPrefix(msg, "Policy Block:") {
				candidateType = "policy_block"
			} else if strings.HasPrefix(msg, "Policy Anomaly:") {
				// Anomaly rules add score but don't block by themselves.
				// Only classify as "policy_anomaly" if the request was not
				// interrupted — if it was blocked, the score contribution
				// pushed it over threshold and "blocked" is more accurate.
				if !tx.IsInterrupted {
					candidateType = "policy_anomaly"
				}
			}
			break // policy classification takes absolute priority
		}
	}
	if candidateType != "" {
		eventType = candidateType
	}

	// Extract policy tags from matched rules. Tags prefixed with "policy:"
	// are user-defined classification tags emitted by the generator.
	var policyTags []string
	for _, m := range entry.Messages {
		for _, t := range m.Data.Tags {
			if strings.HasPrefix(t, "policy:") {
				policyTags = append(policyTags, strings.TrimPrefix(t, "policy:"))
			}
		}
	}
	// Deduplicate tags (multiple rules may carry the same tag).
	policyTags = dedupeTags(policyTags)

	// When Coraza blocks a request (is_interrupted), the backend never responds,
	// so response.status is 0 in the audit log. Show 403 since that's what the
	// client actually receives.
	status := tx.Response.Status
	if tx.IsInterrupted && status == 0 {
		status = 403
	}

	// Use the Caddy request UUID (X-Request-Id) as the event ID when available.
	// This gives every request a single ID shared across security events
	// and general logs. Falls back to Coraza's transaction ID for audit log
	// entries that predate the X-Request-Id header injection.
	eventID := tx.ID
	if rid := headerValue(tx.Request.Headers, "X-Request-Id"); rid != "" {
		eventID = rid
	}

	ev := Event{
		ID:             eventID,
		Timestamp:      ts,
		ClientIP:       tx.ClientIP,
		Service:        tx.ServerID,
		Method:         tx.Request.Method,
		URI:            tx.Request.URI,
		Protocol:       tx.Request.Protocol,
		IsBlocked:      tx.IsInterrupted,
		ResponseStatus: status,
		UserAgent:      ua,
		EventType:      eventType,
		Tags:           policyTags,
	}

	// Extract rule match data from the messages array (audit log part H).
	// Use the highest-severity (lowest number) matched rule as the primary.
	if len(entry.Messages) > 0 {
		best := entry.Messages[0]
		for _, m := range entry.Messages[1:] {
			// Lower severity number = higher severity. 0 means unset.
			if m.Data.Severity > 0 && (best.Data.Severity == 0 || m.Data.Severity < best.Data.Severity) {
				best = m
			}
			// Prefer rules with an actual ID (skip anomaly scoring rules).
			if scoringRuleIDs[best.Data.ID] {
				if !isScoringRule(m.Data.ID) {
					best = m
				}
			}
		}
		ev.RuleID = best.Data.ID
		ev.RuleMsg = best.Data.Msg
		ev.Severity = best.Data.Severity
		ev.MatchedData = best.Data.Data
		ev.RuleTags = best.Data.Tags

		// Extract inbound and outbound anomaly scores separately.
		//
		// Priority order for each score:
		//   1. Rule 949110 (inbound) / 959100 (outbound) — blocking evaluation rules
		//      that fire when the score exceeds the threshold. Message: "Total Score: N"
		//   2. Rule 980170 — phase 5 correlation/reporting rule that logs a full breakdown
		//      of all scores. Message: "Anomaly Scores: (Inbound Scores: blocking=N, ...)
		//      - (Outbound Scores: blocking=N, ...)"
		//   3. Fallback: sum CRS severity-based points from matched rules, filtered by
		//      ID range (inbound: 910000-949999, outbound: 950000-979999).
		var saw949110, saw959100 bool
		for _, m := range entry.Messages {
			switch m.Data.ID {
			case 949110:
				ev.AnomalyScore = extractAnomalyScore(m.Data.Msg)
				saw949110 = true
			case 959100:
				ev.OutboundAnomalyScore = extractAnomalyScore(m.Data.Msg)
				saw959100 = true
			case 980170:
				// 980170 contains both scores — use as fallback for whichever
				// wasn't already set by 949110/959100.
				inbound, outbound := extractScoresFrom980170(m.Data.Msg)
				if ev.AnomalyScore == 0 {
					ev.AnomalyScore = inbound
				}
				if ev.OutboundAnomalyScore == 0 {
					ev.OutboundAnomalyScore = outbound
				}
			}
		}
		// Last resort: compute from individual rule severities.
		if ev.AnomalyScore == 0 {
			ev.AnomalyScore = computeAnomalyScoreByPhase(entry.Messages, false)
		}
		if ev.OutboundAnomalyScore == 0 {
			ev.OutboundAnomalyScore = computeAnomalyScoreByPhase(entry.Messages, true)
		}

		// Determine how the request was blocked.
		if ev.IsBlocked {
			if saw949110 {
				ev.BlockedBy = "anomaly_inbound"
			} else if saw959100 {
				ev.BlockedBy = "anomaly_outbound"
			} else {
				ev.BlockedBy = "direct"
			}
		}

		// Collect all matched rules (skip scoring/evaluation rules).
		seen := make(map[int]bool)
		for _, m := range entry.Messages {
			id := m.Data.ID
			if isScoringRule(id) {
				continue
			}
			if seen[id] {
				continue
			}
			seen[id] = true
			ev.MatchedRules = append(ev.MatchedRules, MatchedRule{
				ID:          id,
				Msg:         m.Data.Msg,
				Severity:    m.Data.Severity,
				MatchedData: m.Data.Data,
				File:        m.Data.File,
				Tags:        m.Data.Tags,
			})
		}
	}

	// RequestID = Caddy UUID for cross-log correlation. When the unified
	// request ID is active (eventID != tx.ID), both fields carry the same value.
	if rid := headerValue(tx.Request.Headers, "X-Request-Id"); rid != "" {
		ev.RequestID = rid
	}

	// Attach request context for full payload inspection.
	if len(tx.Request.Headers) > 0 {
		ev.RequestHeaders = tx.Request.Headers
	}
	if tx.Request.Body != "" {
		ev.RequestBody = tx.Request.Body
	}
	if len(tx.Request.Args) > 0 {
		ev.RequestArgs = tx.Request.Args
	}

	return ev
}

// --- Anomaly Score Extraction ---

// extractAnomalyScore parses "Total Score: N" from CRS anomaly evaluation rule messages.
// Returns 0 if the pattern is not found.
func extractAnomalyScore(msg string) int {
	const prefix = "Total Score: "
	idx := strings.Index(msg, prefix)
	if idx < 0 {
		return 0
	}
	rest := msg[idx+len(prefix):]
	// Read digits until non-digit or end.
	end := 0
	for end < len(rest) && rest[end] >= '0' && rest[end] <= '9' {
		end++
	}
	if end == 0 {
		return 0
	}
	score, err := strconv.Atoi(rest[:end])
	if err != nil {
		return 0
	}
	return score
}

// extractScoresFrom980170 parses both inbound and outbound blocking scores from
// rule 980170's correlation message. Format:
//
//	"Anomaly Scores: (Inbound Scores: blocking=N, ...) - (Outbound Scores: blocking=N, ...)"
//
// Returns (inbound, outbound). Returns 0 for either if not found.
func extractScoresFrom980170(msg string) (int, int) {
	inbound := extractNamedScore(msg, "Inbound Scores: blocking=")
	outbound := extractNamedScore(msg, "Outbound Scores: blocking=")
	return inbound, outbound
}

// extractNamedScore extracts an integer after the given prefix in a message.
// E.g. extractNamedScore("...blocking=15,...", "blocking=") returns 15.
func extractNamedScore(msg, prefix string) int {
	idx := strings.Index(msg, prefix)
	if idx < 0 {
		return 0
	}
	rest := msg[idx+len(prefix):]
	end := 0
	for end < len(rest) && rest[end] >= '0' && rest[end] <= '9' {
		end++
	}
	if end == 0 {
		return 0
	}
	score, err := strconv.Atoi(rest[:end])
	if err != nil {
		return 0
	}
	return score
}

// computeAnomalyScoreByPhase sums CRS severity-based anomaly points from
// matched rules, filtered by CRS rule ID range (inbound vs outbound).
//
// CRS 4.x ID ranges:
//
//	Inbound  (request phases 1-2):  910000-949999
//	Outbound (response phases 3-4): 950000-979999
//
// CRS 4.x scoring: CRITICAL(2)=5, ERROR(3)=4, WARNING(4)=3, NOTICE(5)=2.
// Evaluation/scoring rules and ID 0 are excluded.
func computeAnomalyScoreByPhase(messages []AuditMessage, outbound bool) int {
	score := 0
	seen := make(map[int]bool) // deduplicate by rule ID (chain rules repeat)
	for _, m := range messages {
		id := m.Data.ID
		if isScoringRule(id) {
			continue
		}
		if seen[id] {
			continue
		}
		// Filter by CRS rule ID range.
		isOutbound := id >= crsOutboundMin && id <= crsOutboundMax
		if outbound != isOutbound {
			continue
		}
		seen[id] = true
		score += severityScoreMap[m.Data.Severity]
	}
	return score
}

// computeAnomalyScore sums CRS severity-based anomaly points from all matched
// rules (both inbound and outbound). This is the combined total score.
// Kept for backward compatibility with tests; prefer computeAnomalyScoreByPhase.
func computeAnomalyScore(messages []AuditMessage) int {
	return computeAnomalyScoreByPhase(messages, false) + computeAnomalyScoreByPhase(messages, true)
}

// parseTimestamp parses Coraza's "2006/01/02 15:04:05" format.
func parseTimestamp(raw string) time.Time {
	t, err := time.Parse("2006/01/02 15:04:05", raw)
	if err != nil {
		return time.Time{}
	}
	return t.UTC()
}
