import type { WAFEvent } from "@/lib/api";

export const SEVERITY_MAP: Record<number, { label: string; color: string }> = {
  2: { label: "CRITICAL", color: "text-neon-pink" },
  3: { label: "ERROR", color: "text-neon-amber" },
  4: { label: "WARNING", color: "text-yellow-400" },
  5: { label: "NOTICE", color: "text-neon-blue" },
};

export function formatSeverity(severity: number): { label: string; color: string } {
  return SEVERITY_MAP[severity] ?? { label: severity ? `Level ${severity}` : "N/A", color: "text-muted-foreground" };
}

/** Parse CRS matched_data string into structured parts. */
export function parseMatchedData(raw: string): { trigger: string; variable: string; fullValue: string } | null {
  // Format: "Matched Data: <trigger> found within <VARIABLE>: <full_value>"
  const m = raw.match(/^Matched Data:\s*(.+?)\s+found within\s+(\S+?):\s*(.+)$/s);
  if (m) return { trigger: m[1], variable: m[2], fullValue: m[3] };
  return null;
}

/** Render text with all occurrences of `highlight` wrapped in a highlight span. */
export function HighlightedText({ text, highlight }: { text: string; highlight: string }) {
  if (!highlight || !text) return <>{text}</>;
  // Escape regex special chars in the highlight string
  const escaped = highlight.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const parts = text.split(new RegExp(`(${escaped})`, "gi"));
  return (
    <>
      {parts.map((part, i) =>
        part.toLowerCase() === highlight.toLowerCase() ? (
          <mark key={i} className="bg-neon-amber/25 text-neon-amber rounded px-0.5">{part}</mark>
        ) : (
          <span key={i}>{part}</span>
        )
      )}
    </>
  );
}

/** Extract the exclusion name from a Policy Engine rule message.
 * Messages follow the pattern: "Policy Skip: <name>", "Policy Allow: <name>", "Policy Block: <name>".
 * Returns the name portion, or null if the message doesn't match. */
export function extractPolicyRuleName(ruleMsg: string | undefined): string | null {
  if (!ruleMsg) return null;
  const m = ruleMsg.match(/^Policy (?:Skip|Allow|Block):\s*(.+)$/);
  return m ? m[1] : null;
}

/** Build a URL to the Policy Engine page that highlights a specific exclusion by name. */
export function policyRuleLink(ruleMsg: string | undefined): string | null {
  const name = extractPolicyRuleName(ruleMsg);
  if (!name) return null;
  return `/policy?rule=${encodeURIComponent(name)}`;
}

/** Returns true if the event was generated by a Policy Engine rule (95xxxxx range). */
export function isPolicyRuleEvent(event: WAFEvent): boolean {
  return event.rule_id >= 9500000 && event.rule_id <= 9599999;
}
