#!/bin/sh
# update-ipsum.sh — Fetch IPsum threat intelligence and generate a Caddy-importable blocklist.
# Runs inside the Caddy container via crond. Also usable standalone.
#
# IPsum: https://github.com/stamparm/ipsum

set -eu

IPSUM_URL="https://raw.githubusercontent.com/stamparm/ipsum/master/ipsum.txt"
MIN_SCORE="${IPSUM_MIN_SCORE:-3}"
OUTPUT_FILE="${IPSUM_OUTPUT:-/data/coraza/ipsum_block.caddy}"
TMP_FILE="${OUTPUT_FILE}.tmp"

log() { printf '[ipsum] %s %s\n' "$(date -Iseconds)" "$*"; }

log "Starting IPsum blocklist update (min_score=${MIN_SCORE})"

# Fetch the raw list
raw=$(curl -fsSL --retry 3 --retry-delay 5 --max-time 60 "${IPSUM_URL}")

# Filter IPs by score
ips=$(echo "${raw}" | awk -v min="${MIN_SCORE}" '
    /^#/ { next }
    /^[[:space:]]*$/ { next }
    { if ($2+0 >= min) print $1 }
')

count=$(echo "${ips}" | wc -l)
log "Found ${count} IPs with score >= ${MIN_SCORE}"

if [ "${count}" -lt 10 ]; then
    log "ERROR: Too few IPs (${count}), aborting to prevent empty blocklist"
    exit 1
fi

# Convert newlines to spaces for the Caddy client_ip matcher
ip_line=$(echo "${ips}" | tr '\n' ' ')

# Generate Caddy-importable snippet
cat > "${TMP_FILE}" <<EOF
# AUTO-GENERATED by update-ipsum.sh — do not edit manually
# Updated: $(date -Iseconds)
# IPs: ${count} (min_score=${MIN_SCORE})
# Source: ${IPSUM_URL}
@ipsum_blocked client_ip ${ip_line}
route @ipsum_blocked {
	header X-Blocked-By ipsum
	respond 403 {
		body "Blocked"
		close
	}
}
EOF

# Atomic replace
mv "${TMP_FILE}" "${OUTPUT_FILE}"
log "Wrote ${count} IPs to ${OUTPUT_FILE}"

# Reload Caddy (running in the same container).
# The reload can take 60-90s due to Coraza WAF + rate limit zone initialization.
if caddy reload --config /etc/caddy/Caddyfile --adapter caddyfile 2>/dev/null; then
    log "Caddy reloaded successfully"
else
    log "WARNING: Caddy reload failed (may need manual reload)"
fi

log "Done"
