import { Fragment, useState, useEffect, useCallback, useRef, useMemo } from "react";
import {
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ChevronsLeft,
  ChevronsRight,
  ChevronsDownUp,
  Download,
  ShieldPlus,
  ExternalLink,
} from "lucide-react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import {
  fetchEvents,
  fetchAllEvents,
  fetchServices,
  getExclusions,
  type WAFEvent,
  type EventsResponse,
  type ServiceDetail,
} from "@/lib/api";
import TimeRangePicker, { rangeToParams, type TimeRange } from "@/components/TimeRangePicker";
import { countryFlag, formatTime, formatDate } from "@/lib/format";
import { EventTypeBadge } from "./EventTypeBadge";
import DashboardFilterBar, {
  parseFiltersFromURL,
  filtersToEventsParams,
  type DashboardFilter,
} from "./DashboardFilterBar";

const SEVERITY_MAP: Record<number, { label: string; color: string }> = {
  2: { label: "CRITICAL", color: "text-neon-pink" },
  3: { label: "ERROR", color: "text-neon-amber" },
  4: { label: "WARNING", color: "text-yellow-400" },
  5: { label: "NOTICE", color: "text-neon-blue" },
};

function formatSeverity(severity: number): { label: string; color: string } {
  return SEVERITY_MAP[severity] ?? { label: severity ? `Level ${severity}` : "N/A", color: "text-muted-foreground" };
}

/** Parse CRS matched_data string into structured parts. */
function parseMatchedData(raw: string): { trigger: string; variable: string; fullValue: string } | null {
  // Format: "Matched Data: <trigger> found within <VARIABLE>: <full_value>"
  const m = raw.match(/^Matched Data:\s*(.+?)\s+found within\s+(\S+?):\s*(.+)$/s);
  if (m) return { trigger: m[1], variable: m[2], fullValue: m[3] };
  return null;
}

/** Render text with all occurrences of `highlight` wrapped in a highlight span. */
function HighlightedText({ text, highlight }: { text: string; highlight: string }) {
  if (!highlight || !text) return <>{text}</>;
  // Escape regex special chars in the highlight string
  const escaped = highlight.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const parts = text.split(new RegExp(`(${escaped})`, "gi"));
  return (
    <>
      {parts.map((part, i) =>
        part.toLowerCase() === highlight.toLowerCase() ? (
          <mark key={i} className="bg-neon-amber/25 text-neon-amber rounded px-0.5">{part}</mark>
        ) : (
          <span key={i}>{part}</span>
        )
      )}
    </>
  );
}

/** Extract the exclusion name from a Policy Engine rule message.
 * Messages follow the pattern: "Policy Skip: <name>", "Policy Allow: <name>", "Policy Block: <name>".
 * Returns the name portion, or null if the message doesn't match. */
function extractPolicyRuleName(ruleMsg: string | undefined): string | null {
  if (!ruleMsg) return null;
  const m = ruleMsg.match(/^Policy (?:Skip|Allow|Block):\s*(.+)$/);
  return m ? m[1] : null;
}

/** Build a URL to the Policy Engine page that highlights a specific exclusion by name. */
function policyRuleLink(ruleMsg: string | undefined): string | null {
  const name = extractPolicyRuleName(ruleMsg);
  if (!name) return null;
  return `/policy?rule=${encodeURIComponent(name)}`;
}

/** Returns true if the event was generated by a Policy Engine rule (95xxxxx range). */
function isPolicyRuleEvent(event: WAFEvent): boolean {
  return event.rule_id >= 9500000 && event.rule_id <= 9599999;
}

export function EventDetailPanel({ event }: { event: WAFEvent }) {
  // Only show "Create Exception" for WAF events (not ipsum/rate-limited/policy-managed/honeypot/scanner)
  const isWafEvent = event.event_type !== "ipsum_blocked"
    && event.event_type !== "rate_limited"
    && event.event_type !== "honeypot"
    && event.event_type !== "scanner"
    && !event.event_type?.startsWith("policy_");

  return (
    <div className="space-y-3 p-4">
      <div className="flex justify-end gap-1.5">
        {isWafEvent && (
          <a
            href="/policy?from_event=1"
            onClick={(e) => {
              e.stopPropagation();
              sessionStorage.setItem("waf:prefill-event", JSON.stringify(event));
            }}
            className="inline-flex"
          >
            <Button
              variant="ghost"
              size="xs"
              className="text-neon-cyan hover:text-neon-green"
              tabIndex={-1}
            >
              <ShieldPlus className="h-3 w-3 mr-1" />
              Create Exception
            </Button>
          </a>
        )}
        <Button
          variant="ghost"
          size="xs"
          className="text-muted-foreground hover:text-foreground"
          onClick={(e) => {
            e.stopPropagation();
            downloadJSON(event, `event-${event.id}.json`);
          }}
        >
          <Download className="h-3 w-3 mr-1" />
          Export JSON
        </Button>
      </div>
      <div className="grid gap-4 md:grid-cols-2">
        <div className="space-y-2">
          <h4 className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
            Request Details
          </h4>
          <div className="space-y-1 rounded-md bg-navy-950 p-3 text-xs">
            <div className="flex gap-2">
              <span className="text-muted-foreground">Method:</span>
              <span className="font-medium text-neon-cyan">{event.method}</span>
            </div>
            <div className="flex gap-2">
              <span className="text-muted-foreground">URI:</span>
              <code className="break-all text-foreground">{event.uri}</code>
            </div>
            <div className="flex gap-2">
              <span className="text-muted-foreground">Client:</span>
              <span className="text-foreground">{event.client_ip}</span>
              {event.country && event.country !== "XX" && (
                <span className="text-muted-foreground">
                  ({countryFlag(event.country)} {event.country})
                </span>
              )}
            </div>
            <div className="flex gap-2">
              <span className="text-muted-foreground">Status:</span>
              <span
                className={
                  event.status >= 400 ? "text-neon-pink" : "text-neon-green"
                }
              >
                {event.status}
              </span>
            </div>
          </div>
        </div>

        <div className="space-y-2">
          <h4 className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
            {event.event_type === "ipsum_blocked" ? "IPsum Blocklist Details"
              : event.event_type === "rate_limited" ? "Rate Limit Details"
              : event.event_type === "honeypot" ? "Honeypot Trap Details"
              : event.event_type === "scanner" ? "Scanner Detection Details"
              : event.event_type?.startsWith("policy_") ? "Policy Engine Match"
              : event.blocked_by === "anomaly_inbound" || event.blocked_by === "anomaly_outbound"
                ? "Anomaly Score Block"
                : "Rule Match"}
          </h4>
          <div className="space-y-1 rounded-md bg-navy-950 p-3 text-xs">
            {event.event_type === "honeypot" ? (
              <>
                <div className="flex gap-2">
                  <span className="text-muted-foreground">Action:</span>
                  <span className="text-orange-400 font-medium">Honeypot Trap (403)</span>
                </div>
                <div className="flex gap-2">
                  <span className="text-muted-foreground">Response:</span>
                  <span className="text-neon-pink">403 Forbidden</span>
                </div>
                {event.rule_msg && (
                  <div className="flex gap-2">
                    <span className="text-muted-foreground">Rule:</span>
                    <span className="text-orange-400">{event.rule_id} — {event.rule_msg}</span>
                  </div>
                )}
                {event.user_agent && (
                  <div className="flex gap-2">
                    <span className="text-muted-foreground">User-Agent:</span>
                    <code className="break-all text-foreground">{event.user_agent}</code>
                  </div>
                )}
              </>
            ) : event.event_type === "scanner" ? (
              <>
                <div className="flex gap-2">
                  <span className="text-muted-foreground">Action:</span>
                  <span className="text-red-400 font-medium">Scanner Detection (403)</span>
                </div>
                <div className="flex gap-2">
                  <span className="text-muted-foreground">Response:</span>
                  <span className="text-neon-pink">403 Forbidden</span>
                </div>
                {event.rule_msg && (
                  <div className="flex gap-2">
                    <span className="text-muted-foreground">Rule:</span>
                    <span className="text-red-400">{event.rule_id} — {event.rule_msg}</span>
                  </div>
                )}
                {event.user_agent && (
                  <div className="flex gap-2">
                    <span className="text-muted-foreground">User-Agent:</span>
                    <code className="break-all text-foreground">{event.user_agent}</code>
                  </div>
                )}
              </>
            ) : event.event_type === "ipsum_blocked" ? (
              <>
                <div className="flex gap-2">
                  <span className="text-muted-foreground">Action:</span>
                  <span className="text-purple-400 font-medium">IPsum Blocklist (403)</span>
                </div>
                <div className="flex gap-2">
                  <span className="text-muted-foreground">Response:</span>
                  <span className="text-neon-pink">403 Forbidden</span>
                </div>
                <div className="flex gap-2">
                  <span className="text-muted-foreground">Source:</span>
                  <span className="text-purple-400">IPsum threat intelligence blocklist</span>
                </div>
                {event.user_agent && (
                  <div className="flex gap-2">
                    <span className="text-muted-foreground">User-Agent:</span>
                    <code className="break-all text-foreground">{event.user_agent}</code>
                  </div>
                )}
              </>
            ) : event.event_type === "rate_limited" ? (
              <>
                <div className="flex gap-2">
                  <span className="text-muted-foreground">Action:</span>
                  <span className="text-yellow-400 font-medium">Rate Limited (429)</span>
                </div>
                <div className="flex gap-2">
                  <span className="text-muted-foreground">Response:</span>
                  <span className="text-neon-pink">429 Too Many Requests</span>
                </div>
                {event.user_agent && (
                  <div className="flex gap-2">
                    <span className="text-muted-foreground">User-Agent:</span>
                    <code className="break-all text-foreground">{event.user_agent}</code>
                  </div>
                )}
              </>
            ) : (
              <>
                {/* Anomaly score block: show the blocking reason prominently */}
                {(event.blocked_by === "anomaly_inbound" || event.blocked_by === "anomaly_outbound") && (
                  <div className="flex gap-2 items-center pb-1 mb-1 border-b border-navy-800">
                    <span className="text-muted-foreground">Blocked By:</span>
                    <span className="text-neon-pink font-medium">
                      {event.blocked_by === "anomaly_inbound"
                        ? `Inbound Anomaly Score (${event.anomaly_score}) exceeded threshold`
                        : `Outbound Anomaly Score (${event.outbound_anomaly_score}) exceeded threshold`}
                    </span>
                  </div>
                )}

                {/* Scores */}
                {(event.anomaly_score > 0 || event.outbound_anomaly_score > 0) && (
                  <div className="flex gap-4">
                    {event.anomaly_score > 0 && (
                      <div className="flex gap-2">
                        <span className="text-muted-foreground">Inbound Score:</span>
                        <span className={
                          event.anomaly_score >= 25 ? "text-neon-pink font-bold" :
                          event.anomaly_score >= 10 ? "text-neon-amber font-medium" :
                          "text-neon-cyan"
                        }>
                          {event.anomaly_score}
                        </span>
                      </div>
                    )}
                    {event.outbound_anomaly_score > 0 && (
                      <div className="flex gap-2">
                        <span className="text-muted-foreground">Outbound Score:</span>
                        <span className={
                          event.outbound_anomaly_score >= 25 ? "text-neon-pink font-bold" :
                          event.outbound_anomaly_score >= 10 ? "text-neon-amber font-medium" :
                          "text-neon-cyan"
                        }>
                          {event.outbound_anomaly_score}
                        </span>
                      </div>
                    )}
                  </div>
                )}

                {/* Primary rule — labeled differently for anomaly vs direct blocks */}
                {event.rule_id > 0 && (
                  <>
                    {(event.blocked_by === "anomaly_inbound" || event.blocked_by === "anomaly_outbound") && (
                      <div className="text-[10px] uppercase tracking-wider text-muted-foreground/60 pt-1">
                        Highest Severity Rule
                      </div>
                    )}
                    <div className="flex gap-2 items-center">
                      <span className="text-muted-foreground">Rule ID:</span>
                      {isPolicyRuleEvent(event) && policyRuleLink(event.rule_msg) ? (
                        <a href={policyRuleLink(event.rule_msg)!} className="inline-flex items-center gap-1 group" onClick={(e) => e.stopPropagation()}>
                          <Badge variant="outline" className="text-[10px] px-1.5 py-0 font-mono group-hover:border-emerald-500/50 group-hover:text-emerald-400 transition-colors">
                            {event.rule_id}
                          </Badge>
                          <ExternalLink className="h-3 w-3 text-muted-foreground group-hover:text-emerald-400 transition-colors" />
                        </a>
                      ) : (
                        <Badge variant="outline" className="text-[10px] px-1.5 py-0 font-mono">
                          {event.rule_id}
                        </Badge>
                      )}
                    </div>
                    <div className="flex gap-2">
                      <span className="text-muted-foreground">Message:</span>
                      {isPolicyRuleEvent(event) && policyRuleLink(event.rule_msg) ? (
                        <a href={policyRuleLink(event.rule_msg)!} className="text-emerald-400 hover:text-emerald-300 hover:underline transition-colors" onClick={(e) => e.stopPropagation()}>
                          {event.rule_msg}
                        </a>
                      ) : (
                        <span className="text-foreground">{event.rule_msg || "N/A"}</span>
                      )}
                    </div>
                    <div className="flex gap-2">
                      <span className="text-muted-foreground">Severity:</span>
                      {(() => {
                        const sev = formatSeverity(event.severity);
                        return <span className={sev.color}>{sev.label}</span>;
                      })()}
                    </div>
                  </>
                )}

                {/* Matched data with parsing and highlighting */}
                {event.matched_data && (() => {
                  const parsed = parseMatchedData(event.matched_data);
                  if (parsed) {
                    return (
                      <div className="space-y-1">
                        <div className="flex gap-2">
                          <span className="text-muted-foreground">Variable:</span>
                          <code className="text-neon-cyan">{parsed.variable}</code>
                        </div>
                        <div className="flex gap-2">
                          <span className="text-muted-foreground">Trigger:</span>
                          <code className="text-neon-amber">{parsed.trigger}</code>
                        </div>
                        <div className="flex gap-2 items-start">
                          <span className="text-muted-foreground shrink-0">Full Value:</span>
                          <code className="break-all text-foreground/80">
                            <HighlightedText text={parsed.fullValue} highlight={parsed.trigger} />
                          </code>
                        </div>
                      </div>
                    );
                  }
                  return (
                    <div className="flex gap-2">
                      <span className="text-muted-foreground">Matched:</span>
                      <code className="break-all text-neon-amber">{event.matched_data}</code>
                    </div>
                  );
                })()}

                {event.rule_tags && event.rule_tags.length > 0 && (
                  <div className="flex flex-wrap gap-1 pt-1">
                    <span className="text-muted-foreground">Tags:</span>
                    {event.rule_tags.map((tag) => (
                      <Badge key={tag} variant="outline" className="text-[9px] px-1 py-0 font-mono text-muted-foreground">
                        {tag}
                      </Badge>
                    ))}
                  </div>
                )}
              </>
            )}
          </div>
        </div>
      </div>

      {/* All Matched Rules (when multiple rules fired) */}
      {event.matched_rules && event.matched_rules.length > 1 && (
        <ExpandableSection title={`All Matched Rules (${event.matched_rules.length})`}>
          <div className="space-y-3">
            {event.matched_rules.map((rule) => {
              const sev = formatSeverity(rule.severity);
              const parsed = rule.matched_data ? parseMatchedData(rule.matched_data) : null;
              return (
                <div key={rule.id} className="rounded border border-navy-800 bg-navy-950/50 p-2 space-y-1 text-xs">
                  <div className="flex items-center gap-2">
                    <Badge variant="outline" className="text-[10px] px-1.5 py-0 font-mono">{rule.id}</Badge>
                    <span className={sev.color + " text-[10px] font-medium"}>{sev.label}</span>
                    <span className="text-foreground/80 truncate">{rule.msg}</span>
                  </div>
                  {parsed ? (
                    <div className="pl-2 space-y-0.5">
                      <div className="flex gap-2">
                        <span className="text-muted-foreground">Variable:</span>
                        <code className="text-neon-cyan">{parsed.variable}</code>
                      </div>
                      <div className="flex gap-2 items-start">
                        <span className="text-muted-foreground shrink-0">Value:</span>
                        <code className="break-all text-foreground/80">
                          <HighlightedText text={parsed.fullValue} highlight={parsed.trigger} />
                        </code>
                      </div>
                    </div>
                  ) : rule.matched_data ? (
                    <div className="pl-2">
                      <code className="break-all text-neon-amber text-[10px]">{rule.matched_data}</code>
                    </div>
                  ) : null}
                  {rule.file && (
                    <div className="pl-2 text-[10px] text-muted-foreground/60">{rule.file}</div>
                  )}
                </div>
              );
            })}
          </div>
        </ExpandableSection>
      )}

      {/* Request Context */}
      {(event.request_args && Object.keys(event.request_args).length > 0) ||
       event.request_body ||
       (event.request_headers && Object.keys(event.request_headers).length > 0) ? (
        <ExpandableSection title="Request Context">
          <div className="space-y-3">
            {event.request_args && Object.keys(event.request_args).length > 0 && (
              <div className="space-y-1">
                <h5 className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground/70">Query / Form Args</h5>
                <div className="rounded border border-navy-800 bg-navy-950/50 p-2">
                  {Object.entries(event.request_args).map(([key, value]) => {
                    const trigger = event.matched_data ? parseMatchedData(event.matched_data)?.trigger : undefined;
                    return (
                      <div key={key} className="flex gap-1 text-xs">
                        <span className="text-neon-cyan shrink-0">{key}:</span>
                        <code className="break-all text-foreground/80">
                          {trigger ? <HighlightedText text={value} highlight={trigger} /> : value}
                        </code>
                      </div>
                    );
                  })}
                </div>
              </div>
            )}

            {event.request_body && (
              <div className="space-y-1">
                <h5 className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground/70">Request Body</h5>
                <div className="rounded border border-navy-800 bg-navy-950/50 p-2">
                  <pre className="text-xs text-foreground/80 whitespace-pre-wrap break-all">
                    {(() => {
                      const trigger = event.matched_data ? parseMatchedData(event.matched_data)?.trigger : undefined;
                      return trigger
                        ? <HighlightedText text={event.request_body} highlight={trigger} />
                        : event.request_body;
                    })()}
                  </pre>
                </div>
              </div>
            )}

            {event.request_headers && Object.keys(event.request_headers).length > 0 && (
              <div className="space-y-1">
                <h5 className="text-[10px] font-medium uppercase tracking-wider text-muted-foreground/70">Headers</h5>
                <div className="rounded border border-navy-800 bg-navy-950/50 p-2 font-mono text-xs">
                  {Object.entries(event.request_headers).map(([k, v]) => {
                    const value = Array.isArray(v) ? v.join(", ") : v;
                    const trigger = event.matched_data ? parseMatchedData(event.matched_data)?.trigger : undefined;
                    return (
                      <div key={k} className="flex gap-0 leading-relaxed">
                        <span className="text-neon-cyan shrink-0">{k}</span>
                        <span className="text-muted-foreground/50">:&nbsp;</span>
                        <span className="text-foreground/80 break-all">
                          {trigger ? <HighlightedText text={value} highlight={trigger} /> : value}
                        </span>
                      </div>
                    );
                  })}
                </div>
              </div>
            )}
          </div>
        </ExpandableSection>
      ) : null}
    </div>
  );
}

/** Download data as a JSON file. */
function downloadJSON(data: unknown, filename: string) {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

/** Collapsible section for the detail panel. */
function ExpandableSection({ title, children }: { title: string; children: React.ReactNode }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="space-y-2">
      <button
        onClick={() => setOpen(!open)}
        className="flex items-center gap-1 text-xs font-medium uppercase tracking-wider text-muted-foreground hover:text-foreground transition-colors"
      >
        {open ? <ChevronDown className="h-3 w-3" /> : <ChevronRight className="h-3 w-3" />}
        {title}
      </button>
      {open && <div className="pl-4">{children}</div>}
    </div>
  );
}

export default function EventsTable() {
  const [response, setResponse] = useState<EventsResponse | null>(null);
  const [services, setServices] = useState<ServiceDetail[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [expanded, setExpanded] = useState<Set<string>>(new Set());

  // Time range
  const [timeRange, setTimeRange] = useState<TimeRange>({
    type: "relative",
    hours: 24,
    label: "Last 24 hours",
  });

  // Filters — shared DashboardFilterBar state
  const [filters, setFilters] = useState<DashboardFilter[]>([]);
  const filtersInitRef = useRef(false);

  // Read URL params on mount (client-only to avoid hydration mismatch)
  useEffect(() => {
    if (filtersInitRef.current) return;
    filtersInitRef.current = true;
    if (typeof window === "undefined") return;
    const search = window.location.search;
    if (!search) return;
    const parsed = parseFiltersFromURL(search);
    if (parsed.length > 0) {
      setFilters(parsed);
      window.history.replaceState({}, "", window.location.pathname);
    }
  }, []);

  const [page, setPage] = useState(1);
  const perPage = 25;

  // Service names for filter bar autocomplete
  const serviceNames = useMemo(
    () => services.map((s) => s.service),
    [services],
  );

  // Rule names for filter bar autocomplete
  const [ruleNames, setRuleNames] = useState<string[]>([]);
  const [exportingAll, setExportingAll] = useState(false);

  const loadEvents = useCallback(() => {
    setLoading(true);
    const timeParams = rangeToParams(timeRange);
    const filterParams = filtersToEventsParams(filters);
    fetchEvents({
      page,
      per_page: perPage,
      ...filterParams,
      ...timeParams,
    })
      .then(setResponse)
      .catch((err) => setError(err.message))
      .finally(() => setLoading(false));
  }, [page, filters, timeRange]);

  useEffect(() => {
    fetchServices()
      .then(setServices)
      .catch(() => {}); // Non-critical
    getExclusions()
      .then((excl) => setRuleNames(excl.map((e) => e.name).filter(Boolean)))
      .catch(() => {}); // Non-critical
  }, []);

  useEffect(() => {
    loadEvents();
  }, [loadEvents]);

  // Reset page when filters change
  useEffect(() => {
    setPage(1);
  }, [filters, timeRange]);

  const toggleExpand = (id: string) => {
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const events = response?.events ?? [];
  const totalPages = response?.total_pages ?? 1;

  if (error) {
    return (
      <Card className="max-w-md">
        <CardHeader>
          <CardTitle className="text-neon-pink">Error</CardTitle>
          <CardDescription>{error}</CardDescription>
        </CardHeader>
      </Card>
    );
  }

  return (
    <div className="space-y-4">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h2 className="text-lg font-semibold">Event Log</h2>
          <p className="text-sm text-muted-foreground">
            All WAF and rate limit events with filtering and detail view.
          </p>
        </div>
        <TimeRangePicker
          value={timeRange}
          onChange={setTimeRange}
          onRefresh={loadEvents}
        />
      </div>

      {/* Filters */}
      <div className="flex flex-wrap items-center gap-3">
        <div className="flex-1 min-w-0">
          <DashboardFilterBar
            filters={filters}
            onChange={setFilters}
            services={serviceNames}
            ruleNames={ruleNames}
          />
        </div>

        {response && (
          <div className="flex items-center gap-2 shrink-0">
            <span className="text-xs text-muted-foreground">
              {response.total.toLocaleString()} events
            </span>
            <div className="flex gap-1">
              <Button
                variant="ghost"
                size="xs"
                className="text-muted-foreground hover:text-foreground"
                onClick={() => downloadJSON(events, `events-page-${page}.json`)}
                title="Export current page as JSON"
              >
                <Download className="h-3 w-3 mr-1" />
                Page
              </Button>
              <Button
                variant="ghost"
                size="xs"
                className="text-muted-foreground hover:text-foreground"
                disabled={exportingAll}
                onClick={async () => {
                  setExportingAll(true);
                  try {
                    const timeParams = rangeToParams(timeRange);
                    const filterParams = filtersToEventsParams(filters);
                    const all = await fetchAllEvents({
                      ...filterParams,
                      ...timeParams,
                    });
                    downloadJSON(all, `events-all-${new Date().toISOString().slice(0, 10)}.json`);
                  } catch {
                    // Best-effort: alert on failure since this is a transient action
                    alert("Failed to export events. Please try again.");
                  } finally {
                    setExportingAll(false);
                  }
                }}
                title="Export all matching events as JSON"
              >
                {exportingAll ? (
                  "Exporting..."
                ) : (
                  <>
                    <Download className="h-3 w-3 mr-1" />
                    All ({response.total.toLocaleString()})
                  </>
                )}
              </Button>
              {expanded.size > 0 && (
                <Button
                  variant="ghost"
                  size="xs"
                  className="text-muted-foreground hover:text-foreground"
                  onClick={() => setExpanded(new Set())}
                  title="Collapse all expanded rows"
                >
                  <ChevronsDownUp className="h-3 w-3 mr-1" />
                  Collapse ({expanded.size})
                </Button>
              )}
            </div>
          </div>
        )}
      </div>

      {/* Events Table */}
      <Card>
        <CardContent className="p-0">
          <Table>
            <TableHeader>
              <TableRow className="hover:bg-transparent">
                <TableHead className="w-8" />
                <TableHead>Time</TableHead>
                <TableHead>Service</TableHead>
                <TableHead>Method</TableHead>
                <TableHead className="max-w-[200px]">URI</TableHead>
                <TableHead>Client IP</TableHead>
                <TableHead>Country</TableHead>
                <TableHead>Rule</TableHead>
                <TableHead title="Inbound / Outbound anomaly score">Score</TableHead>
                <TableHead>Type</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {loading &&
                [...Array(10)].map((_, i) => (
                  <TableRow key={i}>
                    <TableCell />
                    {[...Array(9)].map((_, j) => (
                      <TableCell key={j}>
                        <Skeleton className="h-4 w-full" />
                      </TableCell>
                    ))}
                  </TableRow>
                ))}

              {!loading &&
                events.map((evt) => (
                  <Fragment key={evt.id}>
                    <TableRow
                      className="cursor-pointer"
                      onClick={() => toggleExpand(evt.id)}
                    >
                      <TableCell className="w-8">
                        {expanded.has(evt.id) ? (
                          <ChevronDown className="h-4 w-4 text-muted-foreground" />
                        ) : (
                          <ChevronRight className="h-4 w-4 text-muted-foreground" />
                        )}
                      </TableCell>
                      <TableCell className="whitespace-nowrap text-xs">
                        <div className="text-foreground">
                          {formatTime(evt.timestamp)}
                        </div>
                        <div className="text-muted-foreground">
                          {formatDate(evt.timestamp)}
                        </div>
                      </TableCell>
                      <TableCell className="text-xs">{evt.service}</TableCell>
                      <TableCell>
                        <Badge
                          variant="outline"
                          className="text-[10px] font-mono px-1.5 py-0"
                        >
                          {evt.method}
                        </Badge>
                      </TableCell>
                      <TableCell className="max-w-[200px] truncate text-xs font-mono">
                        {evt.uri}
                      </TableCell>
                      <TableCell className="text-xs font-mono">
                        {evt.client_ip}
                      </TableCell>
                      <TableCell className="text-xs">
                        {evt.country && evt.country !== "XX" ? (
                          <span className="inline-flex items-center gap-1">
                            <span>{countryFlag(evt.country)}</span>
                            <span className="font-mono">{evt.country}</span>
                          </span>
                        ) : (
                          <span className="text-muted-foreground">-</span>
                        )}
                      </TableCell>
                      <TableCell className="text-xs">
                        {evt.rule_id ? (
                          isPolicyRuleEvent(evt) && policyRuleLink(evt.rule_msg) ? (
                            <a href={policyRuleLink(evt.rule_msg)!} className="inline-flex items-center gap-1 group" onClick={(e) => e.stopPropagation()}>
                              <Badge variant="outline" className="text-[10px] px-1.5 py-0 font-mono group-hover:border-emerald-500/50 group-hover:text-emerald-400 transition-colors">
                                {evt.rule_id}
                              </Badge>
                            </a>
                          ) : (
                            <Badge variant="outline" className="text-[10px] px-1.5 py-0 font-mono">
                              {evt.rule_id}
                            </Badge>
                          )
                        ) : (
                          <span className="text-muted-foreground">-</span>
                        )}
                      </TableCell>
                      <TableCell className="text-xs tabular-nums">
                        {evt.anomaly_score > 0 || evt.outbound_anomaly_score > 0 ? (
                          <span className="flex items-center gap-1">
                            <span className={
                              evt.anomaly_score >= 25 ? "text-neon-pink font-bold" :
                              evt.anomaly_score >= 10 ? "text-neon-amber font-medium" :
                              evt.anomaly_score > 0 ? "text-neon-cyan" :
                              "text-muted-foreground"
                            }>
                              {evt.anomaly_score || 0}
                            </span>
                            {evt.outbound_anomaly_score > 0 && (
                              <>
                                <span className="text-muted-foreground">/</span>
                                <span className={
                                  evt.outbound_anomaly_score >= 25 ? "text-neon-pink font-bold" :
                                  evt.outbound_anomaly_score >= 10 ? "text-neon-amber font-medium" :
                                  "text-neon-cyan"
                                }>
                                  {evt.outbound_anomaly_score}
                                </span>
                              </>
                            )}
                          </span>
                        ) : (
                          <span className="text-muted-foreground">-</span>
                        )}
                      </TableCell>
                      <TableCell>
                        <EventTypeBadge eventType={evt.event_type} blocked={evt.blocked} />
                      </TableCell>
                    </TableRow>
                    {expanded.has(evt.id) && (
                      <TableRow className="hover:bg-transparent">
                        <TableCell colSpan={10} className="bg-navy-950/50 p-0">
                          <EventDetailPanel event={evt} />
                        </TableCell>
                      </TableRow>
                    )}
                  </Fragment>
                ))}

              {!loading && events.length === 0 && (
                <TableRow>
                  <TableCell
                    colSpan={10}
                    className="py-8 text-center text-muted-foreground"
                  >
                    No events found matching the current filters.
                  </TableCell>
                </TableRow>
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="flex items-center justify-between">
          <span className="text-xs text-muted-foreground">
            Page {page} of {totalPages}
          </span>
          <div className="flex items-center gap-1">
            <Button
              variant="outline"
              size="icon"
              onClick={() => setPage(1)}
              disabled={page <= 1}
            >
              <ChevronsLeft className="h-4 w-4" />
            </Button>
            <Button
              variant="outline"
              size="icon"
              onClick={() => setPage((p) => Math.max(1, p - 1))}
              disabled={page <= 1}
            >
              <ChevronLeft className="h-4 w-4" />
            </Button>
            <Button
              variant="outline"
              size="icon"
              onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
              disabled={page >= totalPages}
            >
              <ChevronRight className="h-4 w-4" />
            </Button>
            <Button
              variant="outline"
              size="icon"
              onClick={() => setPage(totalPages)}
              disabled={page >= totalPages}
            >
              <ChevronsRight className="h-4 w-4" />
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}
